name: Artifacts

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libudev-dev
      - name: Setup toolchain
        run: |
          rustup update stable
          rustup default stable
          rustup set profile minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ebc-battery-tester-linux
          path: target/release/ebc_battery_tester

  build-windows:
    runs-on: windows-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Setup toolchain
        run: |
          rustup update stable
          rustup default stable
          rustup set profile minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ebc-battery-tester-windows
          path: target/release/ebc_battery_tester.exe

  build-wasm:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Setup toolchain
        run: |
          rustup update stable
          rustup default stable
          rustup set profile minimal
          rustup target add wasm32-unknown-unknown
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Build
        run: EBC_WASM_DEFAULT_TRANSPORT=webusb ./trunk build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ebc-battery-tester-wasm
          path: dist/
