name: Github Pages

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  build-github-pages:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # repo checkout
      - name: Setup toolchain for wasm
        run: |
          rustup update stable
          rustup default stable
          rustup set profile minimal
          rustup target add wasm32-unknown-unknown
      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v2
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Build
        run: EBC_WASM_DEFAULT_TRANSPORT=webusb ./trunk build --release --public-url $public_url
        env:
          public_url: "https://mauri.codes/${{ github.event.repository.name }}"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          # this option will not maintain any history of your previous pages
          # deployment set to false if you want all page build to be committed
          # to your gh-pages branch history
          single-commit: true
